#define CMR_COUNT 50
#define PATTERN_FITNESS 
#define CYCLES 16
#define STATES_COUNT 5
#define WIDTH_PARAM 14
#define HEIGHT_PARAM 7
#define MAX_FITNESS HEIGHT_PARAM*WIDTH_PARAM
#define NON_EVAL_CYCLES 4